### PR TITLE
Windows: Keep Logical Volumes locked while writing

### LINKED ISSUE #50: [WIN 10]fwup burning to SD card not working as expected
Log:
fwup -a -i rpi/blinky.fw -t complete
Use 1.89 GiB memory card found at \\.\PhysicalDrive2? [y/N] y
100%
they were never bootable by rpi
and sometimes the .txt files were "jibberish"(broken)
example cmdline.txt: ÂœV¾ƒã|“nÙÄ¶õ[á157T•§ñ´6öœ§ lÑúÆeá*iûÚ–))Žœ(-¶æPÜ»oÕç²º¾È

but writing to .img file then writing it with win32 disk imager to the sd card it works

### PR DESCRIPTION
**Pull request by michaelkschmidt**
This fixes #50

### CODE REVIEW

File: src/mmc_windows.c [hunk 1]
```diff
@@ -166,10 +166,12 @@ static void unmount_volume(LPWSTR volume_name) {
                              &bytes_returned,
                              NULL);
 
-    CloseHandle(volume_handle);
 
     if (!status)
-        fwup_errx(EXIT_FAILURE, "Error unmounting '%S' (Error %lu)", volume_name, GetLastError());
+        fwup_errx(EXIT_FAILURE, "Error unmounting '%S' (Error %lu)", volume_name, GetLastError());   
+
+    // Note we deliberately do not FSCTL_UNLOCK_VOLUME here, as the Logical Volume must
```
Comment (fhunleth) [inline src/mmc_windows.c]: Could you change "we deliberately do not FSCTL_UNLOCK_VOLUME" to "we deliberately do not FSCTL_UNLOCK_VOLUME or call CloseHandle"?

I agree, this looks really weird.

File: docs/build_windows.md [hunk 2]
```diff
@@ -13,6 +13,13 @@ Then, run a static build using the mingw compiler:
 
     export CROSS_COMPILE=x86_64-w64-mingw32
     export CC=$CROSS_COMPILE-gcc
+
+     # These are needed for building choco
+    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
+    echo "deb http://download.mono-project.com/repo/debian wheezy/snapshots/3.12.0 main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
+    sudo apt-get update
+    sudo apt-get install -qq mono-devel mono-gmcs nuget
+
```
Comment (fhunleth) [inline docs/build_windows.md]: Could you separate this change out into a separate commit?
